version: "3.5"
services:
  app:
    build: ./backend
    container_name: binate_app
    working_dir: /var/www/binate/backend
    depends_on:
      - db
    networks:
      - appnet
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/var/www/binate/backend
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=shohag

  webserver:
    image: nginx:1.15
    container_name: binate_nginx
    working_dir: /var/www/binate/backend
    depends_on:
      - app
    networks:
      - appnet
    ports:
      - 8001:80
    volumes:
      - ./backend:/var/www/binate/backend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:11.5-alpine
    container_name: binate_postgres
    networks:
      - appnet
    volumes:
      - /home/shohag/Workspace/Deploy/db_store/myapp:/var/lib/postgres
    environment:
      - POSTGRES_USER=binate
      - POSTGRES_PASSWORD=binate
      - POSTGRES_DB=binate

  redis:
    image: redis:latest
    container_name: binate_redis
    depends_on:
      - app
    ports:
      - "6382:6379"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
