# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-16 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(default='', max_length=200)),
                ('is_super', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('male_or_female', models.CharField(blank=True, default='M', max_length=2, null=True)),
                ('is_first_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('is_primary', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('translated_name', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=8000)),
                ('translated_description', models.CharField(blank=True, max_length=8000)),
                ('unit', models.CharField(blank=True, max_length=1024)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(default='', max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_from', models.BigIntegerField(default=0)),
                ('active_upto', models.BigIntegerField(default=9223372036854775807)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ManyToManyField(related_name='_product_price_+', to='product_catalog.ProductPrice'),
        ),
        migrations.AddField(
            model_name='consoleuser',
            name='email_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_catalog.EmailAddress'),
        ),
        migrations.AddField(
            model_name='consoleuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
