# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleuser',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='consoleuser',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product_catalog.ConsoleUser'),
        ),
    ]
